<?php/*|--------------------------------------------------------------------------| Web Routes|--------------------------------------------------------------------------|| Here is where you can register web routes for your application. These| routes are loaded by the RouteServiceProvider within a group which| contains the "web" middleware group. Now create something great!|
*/
//Auth::routes();Route::get('/', 'Auth\LoginController@showLoginForm');Route::group(['middleware' => 'auth'], function () {	Route::get('/', 'OrdersController@orderslist');		Route::get('/order', 'OrdersController@order');	Route::post('/order', 'OrdersController@order');	Route::get('/order/{id}', 'OrdersController@order');//for edit case	Route::get('generate-pdf','PdfController@generatePDF');	Route::post('generate-pdf','PdfController@generatePDF');
	Route::get('/orderslist', 'OrdersController@orderslist');	Route::post('/orderslist', 'OrdersController@orderslist');	Route::get('/recipe-list/{order_id}', 'RecipesController@index');		Route::get('/manage-recipe/{order_id}', 'RecipesController@manage_recipe');	Route::post('/manage-recipe/{order_id}', 'RecipesController@manage_recipe');		Route::get('/manage-recipe/{order_id}/{recipe_id}', 'RecipesController@manage_recipe'); // for edit	Route::post('/manage-recipe/{order_id}/{recipe_id}', 'RecipesController@manage_recipe');		//Common functions	Route::post('/getFiller', 'OrdersController@getFiller');	Route::post('/getHelp', 'OrdersController@getHelp');		Route::post('/getSubcategory', 'RecipesController@getSubcategory');			//Delete Record throughout the website	Route::post('/deleteRecord', 'HomeController@deleteRecord');});
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
// Registration Routes...
Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register');
// Password Reset Routes...Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');Route::post('/password/reset', 'Auth\ResetPasswordController@reset');